help:
	@echo ""
	@echo "Help:"
	@echo ""
	@echo "help: print this message"
	@echo ""
	@echo ""
	@echo ""
	@echo "In these targets, STACK is a Vertalo stack name or a fqdn"
	@echo "  If standard stack name (e.g. web) then deploy to STACK.vertalo.com"
	@echo "  If fqdn stack name (e.g. v.dlbx.io) then deploy to STACK"
	@echo ""
	@echo "install: install npm dependencies"
	@echo ""
	@echo "dev: run development environment"
	@echo ""

install:
	npm install

dev:
	npm run dev
